INSERT INTO PUBLIC.USER(ID_USER, FULL_NAME) VALUES
(1, 'Kara Zor-El'),
(2, 'Wallace Rudolph West'),
(3, 'Mick Rory'),
(4, 'Dashiell Robert Parr'),
(5, 'Jack Napier'),
(6, 'Nels Van Adder'),
(7, 'Mogo'),
(8, 'Richard John Grayson'),
(9, 'Luke Skywalker'),
(10, 'John Stewart'),
(11, 'Luke Cage'),
(12, 'Vril Dox'),
(13, 'Mari Jiwe McCabe'),
(14, 'Leonard Samson'),
(15, '-'),
(16, 'Anna Marie'),
(17, 'Robert Louis Drake'),
(18, 'Ulysses Klaw'),
(19, 'Clark Joseph Kent (Kal-El)'),
(21, 'Orin'),
(22, 'Lester'),
(23, 'Achille DiBacco'),
(24, '-'),
(25, 'Gamora Zen Whoberi Ben Titan'),
(26, 'Timothy Jackson Drake'),
(27, '-'),
(28, 'Dr. James McDonald Hudson'),
(29, 'John Constantine'),
(30, 'Dane Whitman'),
(31, 'Jonathan Blaze'),
(32, 'Lucian'),
(33, 'Namor McKenzie'),
(34, 'Billy Russo'),
(36, 'Teth-Adam'),
(37, 'Cyberdyne Systems Series 850 Terminator'),
(38, 'Patrick Mulligan'),
(39, 'Ororo Munroe'),
(40, 'Christopher Powell'),
(43, 'Jonothon Evan Starsmore'),
(44, 'Carl Creel'),
(45, 'James Howlett'),
(46, 'Jessica Drew'),
(47, 'Gary Bell'),
(49, 'Laura Kinney'),
(50, 'Arthur Sampson Douglas'),
(51, 'Wade Winston Wilson'),
(52, 'Norrin Radd'),
(53, '-'),
(54, 'Emma Grace Frost'),
(55, 'Barbara Gordon'),
(56, 'Elizabeth Braddock'),
(57, 'Pietro Django Maximoff'),
(60, 'Charles Francis Xavier'),
(61, 'Patricia Walker'),
(62, 'Theresa Rourke Cassidy'),
(63, 'Thanos'),
(65, 'Bartholomew Allen II'),
(66, 'Jean-Paul Beaubier'),
(67, 'Benjamin Reilly'),
(69, 'Theodore Kord'),
(70, 'Clinton Francis Barton'),
(73, 'Bartholomew Henry Allen'),
(74, 'Sethaniel Brundle'),
(75, 'Ronald Raymond'),
(77, 'J''onn J''onzz'),
(79, 'Nicholas Joseph Fury'),
(83, 'Natalia Alianovna Romanova'),
(84, 'Slade Joseph Wilson'),
(87, 'Brian Braddock'),
(88, '-'),
(89, 'James Tiberius Kirk'),
(91, 'Ryan Choi'),
(92, 'Daniel Lawrence Hawkins'),
(93, 'Anthony Edward Stark'),
(94, 'Matthew Michael Murdock'),
(95, 'Henry Philip McCoy'),
(96, 'Sebastian Hiram Shaw'),
(98, 'En Sabah Nur'),
(100, 'Mohinder Suresh'),
(101, 'Kon-El / Conner Kent'),
(102, 'Laynia Petrovna'),
(103, '-'),
(104, 'Violet Parr'),
(105, '-'),
(106, 'Kakarot'),
(109, 'Clarice Ferguson'),
(112, 'Lorna Sally Dane'),
(113, 'Richard John Grayson'),
(114, 'Jessica Campbell Jones Cage'),
(115, 'Barbara Ann Minerva'),
(116, 'Donald Gill'),
(117, '-'),
(118, 'Timothy Jackson Drake'),
(121, 'Alexander Summers'),
(123, 'Alec Holland'),
(125, 'Anton Vanko'),
(128, 'Erik Magnus Lensherr'),
(130, 'Dinah Laurel Lance'),
(131, 'Philippa Sontag'),
(133, 'Warren Kenneth Worthington III'),
(135, 'Zebediah Killgrave'),
(136, 'Francisco Paco Ramon'),
(137, 'M''gann M''orzz'),
(138, 'Pamela Lillian Isley'),
(140, 'Stephanie Powell'),
(141, 'Metron'),
(143, 'Kallark'),
(145, 'Tyrone Johnson'),
(147, 'Richard Rider'),
(149, 'Sergei Kravinoff'),
(150, 'John Hancock'),
(153, 'Morris Bench'),
(155, 'Kal-El'),
(156, 'Wilson Grant Fisk'),
(159, 'Selina Kyle'),
(161, 'Marc Spector'),
(162, 'Daisy Louise Johnson'),
(164, '-'),
(165, '-'),
(166, 'Herman Schultz'),
(169, 'Steven Gordon'),
(170, 'Bizarro'),
(171, '-'),
(172, 'Michael Jon Carter'),
(173, 'Norman Virgil Osborn'),
(174, 'Phineas Mason'),
(179, 'Fritz von Meyer'),
(180, 'Kara Zor-L'),
(181, 'Helen Takahama'),
(182, 'Garfield Mark Logan'),
(183, 'Micah Sanders'),
(187, 'Felicia Hardy'),
(189, 'Angel Salvadore Bohusk'),
(192, 'Alfred Thaddeus Crane Pennyworth'),
(193, 'Loki Laufeyson'),
(194, 'Thor Odinson'),
(195, 'Richard John Grayson'),
(196, 'Robert Kirkland Langstrom'),
(198, 'Takashi Matsuya'),
(201, 'John J. Rambo'),
(202, 'Henry Jonathan Pym'),
(203, '-'),
(204, '-'),
(205, 'Dr. Theodore Sallis'),
(207, 'Frigga'),
(209, 'Tandy Bowen'),
(210, 'Monica Dawson'),
(212, '-'),
(213, 'Susan Storm Richards'),
(214, 'Harvey Dent'),
(215, 'Ra''s Al Ghul'),
(217, 'Guy Darrin Gardner'),
(218, 'Dr. Karla Sofen'),
(220, 'Victor Zsasz'),
(222, 'Tessa'),
(223, 'Frances Louise Barrison'),
(225, 'Robert Bruce Banner'),
(226, 'Raymond C. Terrill'),
(229, 'Peter Jason Quill'),
(231, '-'),
(234, 'Victor Stone'),
(235, 'Benjamin Jacob Grimm'),
(236, 'Hila'),
(237, 'Daphne Powell');